{
   "jobs": {
      "build_and_test": {
         "container": "docker://l.gcr.io/google/bazel:3.3.1",
         "runs-on": "ubuntu-latest",
         "steps": [
            {
               "name": "Check out source code",
               "uses": "actions/checkout@v1"
            },
            {
               "name": "Tidy and lint",
               "run": "bazel run //tools/tidy"
            },
            {
               "name": "Test style conformance",
               "run": "git diff --exit-code HEAD --"
            },
            {
               "name": "linux_amd64: build and test",
               "run": "bazel test --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //..."
            },
            {
               "name": "darwin_amd64: build and test",
               "run": "bazel build --platforms=@io_bazel_rules_go//go/toolchain:darwin_amd64 //..."
            },
            {
               "name": "freebsd_amd64: build and test",
               "run": "bazel build --platforms=@io_bazel_rules_go//go/toolchain:freebsd_amd64 //cmd/bb_replicator //cmd/bb_storage"
            },
            {
               "name": "windows_amd64: build and test",
               "run": "bazel build --platforms=@io_bazel_rules_go//go/toolchain:windows_amd64 //..."
            }
         ]
      }
   },
   "name": "pull-requests",
   "on": {
      "pull_request": {
         "branches": [
            "master"
         ]
      }
   }
}
